<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="orders.css"?>

<!DOCTYPE orders [

    <!ELEMENT orders (head,order+)>
    <!ELEMENT head ( code, name, price,quantity,total,date,custNo,payMethod)> 
    <!ELEMENT order ( product,quantity,total,date,custNo)>

    <!ELEMENT product (code, name, price)>
    <!ELEMENT code (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT price (#PCDATA)>

    <!ELEMENT quantity (#PCDATA)>
    <!ELEMENT total (#PCDATA)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT custNo (#PCDATA)>
    <!ELEMENT payMethod (#PCDATA)>

    <!ATTLIST orders id CDATA #REQUIRED>
    <!ATTLIST head class CDATA #REQUIRED>
    <!ATTLIST order row CDATA #REQUIRED>
    <!ATTLIST order orderNo CDATA #REQUIRED>
    <!ATTLIST order PaymentMethod CDATA #REQUIRED>
    

    <!ENTITY product001 '
        <code>001</code>
        <name>Edible oil</name>
        <price>90</price>'>

    <!ENTITY product004 '
        <code>004</code>
        <name>P_Biscuits</name>
        <price>10</price>'>

    <!ENTITY product006 '
        <code>006</code>
        <name>Toothbrush</name>
        <price>40</price>'>

    <!ENTITY product008 '
        <code>006</code>
        <name>Cornflakes</name>
        <price>60</price>'>

    <!ENTITY product009 '
        <code>009</code>
        <name>shampoo</name>
        <price>20</price>'>
]>




<orders id="orderXML">
 
    <head class="header">
        <code>Code</code>
        <name>Name</name>
        <price>Price</price>
        <quantity>Qty</quantity>
        <total>Total</total>
        <date>Date</date>
        <custNo>Customer No</custNo>
        <payMethod></payMethod>
    </head>


    <order orderNo="1001" row="01" PaymentMethod="Cash">
        <product>&product001;</product>
        <quantity>3</quantity>
        <total>270</total>
        <date>23/05/2022</date>
        <custNo>9876598765</custNo>
    </order>

    <order orderNo="1002" row="02" PaymentMethod="Cash">
        <product>&product001;</product>
        <quantity>5</quantity>
        <total>450</total>
        <date>23/05/2022</date>
        <custNo>4213598734</custNo>
    </order>
    
    <order orderNo="1003" row="03" PaymentMethod="Cash">
        <product>&product006;</product>
        <quantity>2</quantity>
        <total>80</total>
        <date>23/05/2022</date>
        <custNo>2342342341</custNo>
    </order>
    
    <order orderNo="1004" row="04" PaymentMethod="Online">
        <product>&product009;</product>
        <quantity>15</quantity>
        <total>300</total>
        <date>23/05/2022</date>
        <custNo>8890102345</custNo>
    </order>
    
    <order orderNo="1005" row="05" PaymentMethod="Cash">
        <product>&product001;</product>
        <quantity>1</quantity>
        <total>90</total>
        <date>23/05/2022</date>
        <custNo>7008945671</custNo>
    </order>
    
    <order orderNo="1006" row="06" PaymentMethod="Online">
        <product>&product006;</product>
        <quantity>10</quantity>
        <total>400</total>
        <date>23/05/2022</date>
        <custNo>9090909000</custNo>
    </order>
    
    <order orderNo="1007" row="07" PaymentMethod="Online">
        <product>&product009;</product>
        <quantity>50</quantity>
        <total>1000</total>
        <date>23/05/2022</date>
        <custNo>5437896510</custNo>
    </order>
    
    <order orderNo="1008" row="08" PaymentMethod="Cash">
        <product>&product001;</product>
        <quantity>10</quantity>
        <total>900</total>
        <date>23/05/2022</date>
        <custNo>7879797979</custNo>
    </order>
    
    <order orderNo="1009" row="09" PaymentMethod="Online">
        <product>&product006;</product>
        <quantity>4</quantity>
        <total>160</total>
        <date>24/05/2022</date>
        <custNo>2200222012</custNo>
    </order>

    <order orderNo="1010" row="10" PaymentMethod="Cash">
        <product>&product006;</product>
        <quantity>9</quantity>
        <total>360</total>
        <date>25/05/2022</date>
        <custNo>5467458791</custNo>
    </order>

    <order orderNo="1011" row="11" PaymentMethod="Cash">
        <product>&product009;</product>
        <quantity>6</quantity>
        <total>120</total>
        <date>24/05/2022</date>
        <custNo>4346356289</custNo>
    </order>

    <order orderNo="1012" row="12" PaymentMethod="Cash">
        <product>&product001;</product>
        <quantity>50</quantity>
        <total>4500</total>
        <date>26/05/2022</date>
        <custNo>7645745199</custNo>
    </order>

    <order orderNo="1013" row="13" PaymentMethod="Cash">
        <product>&product009;</product>
        <quantity>2</quantity>
        <total>40</total>
        <date>24/05/2022</date>
        <custNo>7887348888</custNo>
    </order>

    <order orderNo="1014" row="14" PaymentMethod="Cash">
        <product>&product001;</product>
        <quantity>5</quantity>
        <total>450</total>
        <date>24/05/2022</date>
        <custNo>4367543876</custNo>
    </order>

    <order orderNo="1015" row="15" PaymentMethod="Online">
        <product>&product001;</product>
        <quantity>12</quantity>
        <total>1080</total>
        <date>24/05/2022</date>
        <custNo>0880888880</custNo>
    </order>

    <order orderNo="1016" row="16" PaymentMethod="Online">
        <product>&product001;</product>
        <quantity>15</quantity>
        <total>1350</total>
        <date>30/05/2022</date>
        <custNo>4377764728</custNo>
    </order>

    <order orderNo="1017" row="17" PaymentMethod="Online">
        <product>&product001;</product>
        <quantity>20</quantity>
        <total>1800</total>
        <date>24/05/2022</date>
        <custNo>9823473469</custNo>
    </order>

    <order orderNo="1018" row="18" PaymentMethod="Cash">
        <product>&product009;</product>
        <quantity>100</quantity>
        <total>2000</total>
        <date>27/05/2022</date>
        <custNo>8789798999</custNo>
    </order>

    <order orderNo="1019" row="19" PaymentMethod="Cash">
        <product>&product009;</product>
        <quantity>20</quantity>
        <total>400</total>
        <date>23/05/2022</date>
        <custNo>5654638289</custNo>
    </order>

    <order orderNo="1020" row="20" PaymentMethod="Cash">
        <product>&product009;</product>
        <quantity>70</quantity>
        <total>1400</total>
        <date>24/05/2022</date>
        <custNo>9887689456</custNo>
    </order>

    <order orderNo="1021" row="21" PaymentMethod="Cash">
        <product>&product009;</product>
        <quantity>3</quantity>
        <total>60</total>
        <date>26/05/2022</date>
        <custNo>9876598765</custNo>
    </order>

    <order orderNo="1022" row="22" PaymentMethod="Online">
        <product>&product004;</product>
        <quantity>2</quantity>
        <total>20</total>
        <date>27/05/2022</date>
        <custNo>8789798999</custNo>
    </order>

    <order orderNo="1023" row="23" PaymentMethod="Cash">
        <product>&product004;</product>
        <quantity>5</quantity>
        <total>75</total>
        <date>30/05/2022</date>
        <custNo>9823473469</custNo>
    </order>

    <order orderNo="1024" row="24" PaymentMethod="Cash">
        <product>&product009;</product>
        <quantity>20</quantity>
        <total>440</total>
        <date>02/06/2022</date>
        <custNo>9090909000</custNo>
    </order>
    
    <order orderNo="1025" row="25" PaymentMethod="Online">
        <product>&product001;</product>
        <quantity>10</quantity>
        <total>990</total>
        <date>02/06/2022</date>
        <custNo>8789798999</custNo>
    </order>

</orders>